[2025-04-18T14:31:40.561+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T14:31:40.581+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.run_dvc_pipeline scheduled__2025-04-18T13:00:00+00:00 [queued]>
[2025-04-18T14:31:40.592+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.run_dvc_pipeline scheduled__2025-04-18T13:00:00+00:00 [queued]>
[2025-04-18T14:31:40.593+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-18T14:31:40.616+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): run_dvc_pipeline> on 2025-04-18 13:00:00+00:00
[2025-04-18T14:31:40.623+0000] {standard_task_runner.py:72} INFO - Started process 2300 to run task
[2025-04-18T14:31:40.628+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'run_dvc_pipeline', 'scheduled__2025-04-18T13:00:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp24auuf7t']
[2025-04-18T14:31:40.631+0000] {standard_task_runner.py:105} INFO - Job 69: Subtask run_dvc_pipeline
[2025-04-18T14:31:40.656+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-18T14:31:40.695+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.run_dvc_pipeline scheduled__2025-04-18T13:00:00+00:00 [running]> on host e8dafad5cd22
[2025-04-18T14:31:40.697+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-18T14:31:40.812+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='run_dvc_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-18T13:00:00+00:00'
[2025-04-18T14:31:40.814+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T14:31:40.851+0000] {data_pipeline.py:51} INFO - Executing script: /opt/airflow/scripts/dvc_pipeline.py
[2025-04-18T14:33:47.439+0000] {job.py:229} INFO - Heartbeat recovered after 127.00 seconds
[2025-04-18T14:46:16.258+0000] {data_pipeline.py:55} ERROR - Error executing /opt/airflow/scripts/dvc_pipeline.py: Command '['python', '/opt/airflow/scripts/dvc_pipeline.py']' returned non-zero exit status 1.
[2025-04-18T14:46:16.288+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-18T14:46:16.323+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T14:46:16.338+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=run_dvc_pipeline, run_id=scheduled__2025-04-18T13:00:00+00:00, execution_date=20250418T130000, start_date=20250418T143140, end_date=20250418T144616
[2025-04-18T14:46:16.446+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-18T14:46:16.497+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T14:46:16.498+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
