[2025-04-17T07:37:32.466+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T07:37:32.489+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.download_data manual__2025-04-17T07:36:08.743193+00:00 [queued]>
[2025-04-17T07:37:32.505+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.download_data manual__2025-04-17T07:36:08.743193+00:00 [queued]>
[2025-04-17T07:37:32.511+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-17T07:37:32.539+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): download_data> on 2025-04-17 07:36:08.743193+00:00
[2025-04-17T07:37:32.554+0000] {standard_task_runner.py:72} INFO - Started process 116 to run task
[2025-04-17T07:37:32.561+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'download_data', 'manual__2025-04-17T07:36:08.743193+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp7y99e5kl']
[2025-04-17T07:37:32.566+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask download_data
[2025-04-17T07:37:32.597+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-17T07:37:32.643+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.download_data manual__2025-04-17T07:36:08.743193+00:00 [running]> on host f2a4fe2704a3
[2025-04-17T07:37:32.779+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='download_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T07:36:08.743193+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-17T07:36:08.743193+00:00'
[2025-04-17T07:37:32.782+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-17T07:37:32.809+0000] {data_pipeline.py:51} INFO - Executing script: /opt/airflow/scripts/data_acquisition.py
[2025-04-17T07:38:32.716+0000] {data_pipeline.py:53} INFO - Successfully executed: /opt/airflow/scripts/data_acquisition.py
[2025-04-17T07:38:32.721+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-17T07:38:32.748+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-17T07:38:32.750+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=download_data, run_id=manual__2025-04-17T07:36:08.743193+00:00, execution_date=20250417T073608, start_date=20250417T073732, end_date=20250417T073832
[2025-04-17T07:38:32.867+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-17T07:38:32.941+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-17T07:38:32.956+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-17T07:42:44.654+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T07:42:44.682+0000] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: data_pipeline.download_data manual__2025-04-17T07:36:08.743193+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2025-04-17T07:42:44.684+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
