[2025-03-03T04:00:38.474+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T04:00:38.505+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.generate_schema_statistics scheduled__2025-03-03T03:00:00+00:00 [queued]>
[2025-03-03T04:00:38.520+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.generate_schema_statistics scheduled__2025-03-03T03:00:00+00:00 [queued]>
[2025-03-03T04:00:38.521+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-03T04:00:38.549+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): generate_schema_statistics> on 2025-03-03 03:00:00+00:00
[2025-03-03T04:00:38.559+0000] {standard_task_runner.py:72} INFO - Started process 873 to run task
[2025-03-03T04:00:38.563+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'generate_schema_statistics', 'scheduled__2025-03-03T03:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpgwvs_bt9']
[2025-03-03T04:00:38.566+0000] {standard_task_runner.py:105} INFO - Job 30: Subtask generate_schema_statistics
[2025-03-03T04:00:38.590+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T04:00:38.635+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.generate_schema_statistics scheduled__2025-03-03T03:00:00+00:00 [running]> on host b5502d51568b
[2025-03-03T04:00:38.639+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T04:00:38.752+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='generate_schema_statistics' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T03:00:00+00:00'
[2025-03-03T04:00:38.754+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-03T04:00:38.780+0000] {data_pipeline.py:63} INFO - Running script: /opt/airflow/scripts/data_schema_statistics.py
[2025-03-03T04:00:38.851+0000] {data_pipeline.py:67} ERROR - Error executing /opt/airflow/scripts/data_schema_statistics.py: Command '['python', '/opt/airflow/scripts/data_schema_statistics.py']' returned non-zero exit status 2.
[2025-03-03T04:00:38.852+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-03T04:00:38.862+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-03T04:00:38.863+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=generate_schema_statistics, run_id=scheduled__2025-03-03T03:00:00+00:00, execution_date=20250303T030000, start_date=20250303T040038, end_date=20250303T040038
[2025-03-03T04:00:38.901+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T04:00:38.925+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-03T04:00:38.933+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
