[2025-03-03T02:15:48.897+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T02:15:48.920+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.run_tests scheduled__2025-03-03T01:00:00+00:00 [queued]>
[2025-03-03T02:15:48.934+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.run_tests scheduled__2025-03-03T01:00:00+00:00 [queued]>
[2025-03-03T02:15:48.935+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-03T02:15:48.970+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): run_tests> on 2025-03-03 01:00:00+00:00
[2025-03-03T02:15:48.978+0000] {standard_task_runner.py:72} INFO - Started process 588 to run task
[2025-03-03T02:15:48.982+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'run_tests', 'scheduled__2025-03-03T01:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpri_t8t53']
[2025-03-03T02:15:48.990+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask run_tests
[2025-03-03T02:15:49.017+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T02:15:49.075+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.run_tests scheduled__2025-03-03T01:00:00+00:00 [running]> on host 71fb9604a64f
[2025-03-03T02:15:49.078+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T02:15:49.196+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='run_tests' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T01:00:00+00:00'
[2025-03-03T02:15:49.198+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-03T02:15:49.237+0000] {data_pipeline.py:74} INFO - Running unit tests...
[2025-03-03T02:15:51.390+0000] {data_pipeline.py:78} ERROR - Unit tests failed: Command '['pytest', '/opt/airflow/tests']' returned non-zero exit status 2.
[2025-03-03T02:15:51.392+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-03T02:15:51.406+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-03T02:15:51.407+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=run_tests, run_id=scheduled__2025-03-03T01:00:00+00:00, execution_date=20250303T010000, start_date=20250303T021548, end_date=20250303T021551
[2025-03-03T02:15:51.481+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T02:15:51.501+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-03T02:15:51.504+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-03T02:29:06.811+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T02:29:06.849+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.run_tests scheduled__2025-03-03T01:00:00+00:00 [queued]>
[2025-03-03T02:29:06.865+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.run_tests scheduled__2025-03-03T01:00:00+00:00 [queued]>
[2025-03-03T02:29:06.867+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-03T02:29:06.897+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): run_tests> on 2025-03-03 01:00:00+00:00
[2025-03-03T02:29:06.911+0000] {standard_task_runner.py:72} INFO - Started process 401 to run task
[2025-03-03T02:29:06.918+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'run_tests', 'scheduled__2025-03-03T01:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpjkfounfe']
[2025-03-03T02:29:06.923+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask run_tests
[2025-03-03T02:29:06.962+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T02:29:07.014+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.run_tests scheduled__2025-03-03T01:00:00+00:00 [running]> on host b5502d51568b
[2025-03-03T02:29:07.021+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T02:29:07.126+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='run_tests' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T01:00:00+00:00'
[2025-03-03T02:29:07.127+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-03T02:29:07.174+0000] {data_pipeline.py:74} INFO - Running unit tests...
[2025-03-03T02:29:09.752+0000] {data_pipeline.py:78} ERROR - Unit tests failed: Command '['pytest', '/opt/airflow/tests']' returned non-zero exit status 2.
[2025-03-03T02:29:09.754+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-03T02:29:09.767+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-03T02:29:09.771+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=run_tests, run_id=scheduled__2025-03-03T01:00:00+00:00, execution_date=20250303T010000, start_date=20250303T022906, end_date=20250303T022909
[2025-03-03T02:29:09.882+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T02:29:09.919+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-03T02:29:09.921+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
