[2025-03-03T04:01:01.845+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T04:01:01.864+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.run_tests scheduled__2025-03-03T03:00:00+00:00 [queued]>
[2025-03-03T04:01:01.882+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.run_tests scheduled__2025-03-03T03:00:00+00:00 [queued]>
[2025-03-03T04:01:01.883+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-03T04:01:01.907+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): run_tests> on 2025-03-03 03:00:00+00:00
[2025-03-03T04:01:01.928+0000] {standard_task_runner.py:72} INFO - Started process 922 to run task
[2025-03-03T04:01:01.934+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'run_tests', 'scheduled__2025-03-03T03:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpvr_ugupt']
[2025-03-03T04:01:01.937+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask run_tests
[2025-03-03T04:01:01.960+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T04:01:01.996+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.run_tests scheduled__2025-03-03T03:00:00+00:00 [running]> on host b5502d51568b
[2025-03-03T04:01:02.000+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T04:01:02.131+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='run_tests' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T03:00:00+00:00'
[2025-03-03T04:01:02.134+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-03T04:01:02.159+0000] {data_pipeline.py:74} INFO - Running unit tests...
[2025-03-03T04:01:03.870+0000] {data_pipeline.py:78} ERROR - Unit tests failed: Command '['pytest', '/opt/airflow/tests']' returned non-zero exit status 2.
[2025-03-03T04:01:03.871+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-03T04:01:03.882+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-03T04:01:03.884+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=run_tests, run_id=scheduled__2025-03-03T03:00:00+00:00, execution_date=20250303T030000, start_date=20250303T040101, end_date=20250303T040103
[2025-03-03T04:01:03.959+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T04:01:03.984+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-03T04:01:03.986+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
