[2025-03-03T02:27:25.584+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T02:27:25.601+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.preprocess_data manual__2025-03-03T02:27:03.423548+00:00 [queued]>
[2025-03-03T02:27:25.611+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.preprocess_data manual__2025-03-03T02:27:03.423548+00:00 [queued]>
[2025-03-03T02:27:25.612+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-03T02:27:25.635+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): preprocess_data> on 2025-03-03 02:27:03.423548+00:00
[2025-03-03T02:27:25.641+0000] {standard_task_runner.py:72} INFO - Started process 145 to run task
[2025-03-03T02:27:25.645+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'preprocess_data', 'manual__2025-03-03T02:27:03.423548+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmphu6byukm']
[2025-03-03T02:27:25.648+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask preprocess_data
[2025-03-03T02:27:25.672+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T02:27:25.705+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.preprocess_data manual__2025-03-03T02:27:03.423548+00:00 [running]> on host b5502d51568b
[2025-03-03T02:27:25.783+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T02:27:03.423548+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T02:27:03.423548+00:00'
[2025-03-03T02:27:25.785+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-03T02:27:25.804+0000] {data_pipeline.py:63} INFO - Running script: /opt/airflow/scripts/data_preprocessing.py
[2025-03-03T02:27:25.968+0000] {data_pipeline.py:67} ERROR - Error executing /opt/airflow/scripts/data_preprocessing.py: Command '['python', '/opt/airflow/scripts/data_preprocessing.py']' returned non-zero exit status 1.
[2025-03-03T02:27:25.970+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-03T02:27:25.978+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-03T02:27:25.979+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=preprocess_data, run_id=manual__2025-03-03T02:27:03.423548+00:00, execution_date=20250303T022703, start_date=20250303T022725, end_date=20250303T022725
[2025-03-03T02:27:26.024+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T02:27:26.049+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-03T02:27:26.056+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
