[2025-03-03T02:00:40.786+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T02:00:40.802+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.download_data scheduled__2025-03-03T01:00:00+00:00 [queued]>
[2025-03-03T02:00:40.812+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.download_data scheduled__2025-03-03T01:00:00+00:00 [queued]>
[2025-03-03T02:00:40.813+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-03T02:00:40.839+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): download_data> on 2025-03-03 01:00:00+00:00
[2025-03-03T02:00:40.846+0000] {standard_task_runner.py:72} INFO - Started process 168 to run task
[2025-03-03T02:00:40.852+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'download_data', 'scheduled__2025-03-03T01:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp_rgwqdjv']
[2025-03-03T02:00:40.856+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask download_data
[2025-03-03T02:00:40.887+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T02:00:40.942+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.download_data scheduled__2025-03-03T01:00:00+00:00 [running]> on host 71fb9604a64f
[2025-03-03T02:00:40.945+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T02:00:41.042+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='download_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T01:00:00+00:00'
[2025-03-03T02:00:41.045+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-03T02:00:41.065+0000] {data_pipeline.py:63} INFO - Running script: /opt/airflow/scripts/data_acquisition.py
[2025-03-03T02:01:24.119+0000] {data_pipeline.py:65} INFO - Successfully executed: /opt/airflow/scripts/data_acquisition.py
[2025-03-03T02:01:24.121+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-03T02:01:24.134+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-03T02:01:24.136+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=download_data, run_id=scheduled__2025-03-03T01:00:00+00:00, execution_date=20250303T010000, start_date=20250303T020040, end_date=20250303T020124
[2025-03-03T02:01:24.203+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T02:01:24.236+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-03T02:01:24.244+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-03T02:27:09.493+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T02:27:09.507+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.download_data scheduled__2025-03-03T01:00:00+00:00 [queued]>
[2025-03-03T02:27:09.518+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.download_data scheduled__2025-03-03T01:00:00+00:00 [queued]>
[2025-03-03T02:27:09.519+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-03T02:27:09.539+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): download_data> on 2025-03-03 01:00:00+00:00
[2025-03-03T02:27:09.549+0000] {standard_task_runner.py:72} INFO - Started process 97 to run task
[2025-03-03T02:27:09.556+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'download_data', 'scheduled__2025-03-03T01:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpivsslgsv']
[2025-03-03T02:27:09.566+0000] {standard_task_runner.py:105} INFO - Job 2: Subtask download_data
[2025-03-03T02:27:09.593+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T02:27:09.638+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.download_data scheduled__2025-03-03T01:00:00+00:00 [running]> on host b5502d51568b
[2025-03-03T02:27:09.641+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T02:27:09.739+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='download_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T01:00:00+00:00'
[2025-03-03T02:27:09.742+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-03T02:27:09.819+0000] {data_pipeline.py:63} INFO - Running script: /opt/airflow/scripts/data_acquisition.py
[2025-03-03T02:27:10.668+0000] {data_pipeline.py:67} ERROR - Error executing /opt/airflow/scripts/data_acquisition.py: Command '['python', '/opt/airflow/scripts/data_acquisition.py']' returned non-zero exit status 1.
[2025-03-03T02:27:10.669+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-03T02:27:10.675+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-03T02:27:10.676+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=download_data, run_id=scheduled__2025-03-03T01:00:00+00:00, execution_date=20250303T010000, start_date=20250303T022709, end_date=20250303T022710
[2025-03-03T02:27:10.709+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T02:27:10.736+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-03T02:27:10.743+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
